name: todo_app
description: A new Flutter project.
publish_to: "none"
environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  uuid: ^3.0.4
  flutter_native_splash: ^2.3.5
  cupertino_icons: ^1.0.2
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
flutter_native_splash:
  color: "#FBFAFA"
  image: assets/prancheta.png
  android: true
  ios: true
  resize_mode: contain
